export const cardsData = [
	{
		id: 1,
		title: 'Task 1',
		datetime: '22/06/2020 12:00',
		creator: 'John Doe',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim aequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		type: "new",
		priority: "high",
	},
	{
		id: 2,
		title: 'Task 2',
		datetime: '24/06/2020 23:00',
		creator: 'John Doe',
		description: 'Lorem labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur culpa qui officia deserunt mollit anim id est laborum.',
		type: "new",
		priority: "high",
	},
	{
		id: 3,
		title: 'Task 3',
		datetime: '26/06/2020 02:00',
		creator: 'John Doe',
		description: 'Lorem ipsum dolor sit amet, consectetur elit, sed do eiusmod tempor incidiconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		type: "new",
		priority: "high",
	},
	{
		id: 4,
		title: 'Task 3',
		datetime: '26/06/2020 10:00',
		creator: 'John Doe',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehender sunt in culpa qui officia deserunt mollit anim id est laborum.',
		type: "new",
		priority: "high",
	},
	{
		id: 5,
		title: 'Task 3',
		datetime: '26/06/2020 17:00',
		creator: 'John Doe',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
		type: "new",
		priority: "high",
	},
]